// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNb8ABc68tNWeJhKCOBXiFMWaGeQK_Yt0',
    appId: '1:338484162653:web:94c8e1bef33be51c85ddb4',
    messagingSenderId: '338484162653',
    projectId: 'cookit-mobile',
    authDomain: 'cookit-mobile.firebaseapp.com',
    storageBucket: 'cookit-mobile.appspot.com',
    measurementId: 'G-ZCY3SSYZ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6bwBS2OKMvt0as-lWChEJeubx_g3Czc',
    appId: '1:338484162653:android:e3d7c00a893ea84185ddb4',
    messagingSenderId: '338484162653',
    projectId: 'cookit-mobile',
    storageBucket: 'cookit-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHsaJIZC5eJdoFGKm6KtE9_3CdK-C3f4',
    appId: '1:338484162653:ios:3b8ff478b0b9622285ddb4',
    messagingSenderId: '338484162653',
    projectId: 'cookit-mobile',
    storageBucket: 'cookit-mobile.appspot.com',
    iosClientId: '338484162653-ptjicsu1837qk2b2alqe8uf6o9j482qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookitMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUHsaJIZC5eJdoFGKm6KtE9_3CdK-C3f4',
    appId: '1:338484162653:ios:3b8ff478b0b9622285ddb4',
    messagingSenderId: '338484162653',
    projectId: 'cookit-mobile',
    storageBucket: 'cookit-mobile.appspot.com',
    iosClientId: '338484162653-ptjicsu1837qk2b2alqe8uf6o9j482qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookitMobile',
  );
}
